import { GoogleGenAI } from '@google/genai';
import { storagePut } from './storage';

/**
 * Generate an image using Nano Banana (Imagen models)
 * @param prompt - Text description of the image to generate
 * @param mode - 'standard' for Imagen 4.0 or 'pro' for Imagen 4.0 Pro
 * @param referenceImages - Optional array of reference images (not supported by Imagen API yet)
 * @returns URL of the generated image stored in S3
 */
export async function generateImage(options: {
  prompt: string;
  mode: 'standard' | 'pro';
  aspectRatio?: '16:9' | '1:1' | '4:3' | '9:16';
  referenceImages?: Array<{ data: Buffer; mimeType: string }>;
  apiKey: string;
}): Promise<{ imageUrl: string }> {
  const { prompt, mode, aspectRatio = '16:9', apiKey } = options;

  // Initialize Gemini client (default v1beta has all Imagen models)
  const ai = new GoogleGenAI({ apiKey });

  // Select model based on mode
  // Standard: Imagen 4.0 Standard (balanced quality/speed)
  // Pro: Imagen 4.0 Ultra (highest quality, more detailed)
  const modelName = mode === 'pro' 
    ? 'imagen-4.0-ultra-generate-001' 
    : 'imagen-4.0-generate-001';

  try {
    // Generate image using Imagen API
    const response = await ai.models.generateImages({
      model: modelName,
      prompt: prompt,
      config: {
        numberOfImages: 1,
        aspectRatio: aspectRatio,
      },
    });

    // Extract generated image from response
    if (!response.generatedImages || response.generatedImages.length === 0) {
      throw new Error('No image generated by Nano Banana');
    }

    const generatedImage = response.generatedImages[0];
    if (!generatedImage?.image?.imageBytes) {
      throw new Error('No image data in Nano Banana response');
    }

    // Convert base64 to Buffer
    const imageBuffer = Buffer.from(generatedImage.image.imageBytes, 'base64');

    // Upload generated image to S3
    const timestamp = Date.now();
    const randomSuffix = Math.random().toString(36).substring(7);
    const fileKey = `generated-thumbnails/${timestamp}-${randomSuffix}.png`;
    
    const { url } = await storagePut(
      fileKey,
      imageBuffer,
      'image/png'
    );

    return { imageUrl: url };
  } catch (error: any) {
    console.error('[Nano Banana] Generation error:', error);
    throw new Error(`Nano Banana generation failed: ${error.message}`);
  }
}
